# Use an official python runtime as a parent image
FROM ubuntu:latest

# Set the working directory 
WORKDIR /usr/src/app


# copy the contents of current directory to the container
RUN apt-get update
RUN apt-get install -y python3-pip
RUN apt-get install -y nano

COPY . .

RUN pip install --no-cache-dir -r requirements.txt
# RUN apt-get install -y mysql-server 
# RUN apt-get install -y systemctl

# Run load_balancer.py when the container launches 
# CMD ["bash", "-c", "chmod +x initializer_script_lb; ./initializer_script_lb;"]
CMD ["bash", "-c", "python3 shard_manager.py > shard_manager_logs"]
