# Use an official python runtime as a parent image
FROM ubuntu:22.04

# Set the working directory
WORKDIR /usr/src/app


# copy the contents of current directory to the container
# COPY requirements.txt ./

RUN apt-get update
RUN apt-get install -y python3-pip
RUN apt-get install -y nano
RUN apt-get install -y mysql-server 
RUN apt-get install -y systemctl
COPY . .
RUN pip install --no-cache-dir -r requirements.txt


# copy the contents of current directory to the container
CMD ["bash", "-c", "chmod +x initializer_script_server; ./initializer_script_server;"]