# Use an official python runtime as a parent image
FROM ubuntu:latest

# Set the working directory
WORKDIR /usr/src/app


# copy the contents of current directory to the container
COPY . .
# COPY requirements.txt ./

RUN apt-get update
RUN apt-get install -y python3-pip
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get install -y nano
RUN apt-get install -y mysql-server 
RUN apt-get install -y systemctl


# copy the contents of current directory to the container
CMD ["bash", "-c", "python3 while.py"]