#!/bin/bash
systemctl start mysql
mysql -e 'CREATE DATABASE IF NOT EXISTS Metadata;'
mysql -e "CREATE USER 'myuser'@'localhost' IDENTIFIED BY 'mypass';"
mysql -e "GRANT ALL PRIVILEGES ON Metadata.* TO 'myuser'@'localhost';"
python3 load_balancer_rehashed.py



# mysql -e "Use Metadata; Drop table MapT; Drop table ShardT;" 
# mysql -e "Use Student_info; Drop table sh1; Drop table sh2;" 
