#!/bin/bash
systemctl start mysql
mysql -e 'CREATE DATABASE IF NOT EXISTS Metadata;'
mysql -e "CREATE USER 'myuser'@'localhost' IDENTIFIED BY 'mypass';"
mysql -e "GRANT ALL PRIVILEGES ON Metadata.* TO 'myuser'@'localhost';"
python3 combined_lb.py > lb_logs
